commonConfiguration: |-
  appendonly yes
  save ""
  maxmemory-policy volatile-ttl
auth:
  sentinel: true
  password: super-secure-plaintext-password
replica:
  replicaCount: 3
sentinel:
  enabled: true
